spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/movies
    username: postgres
    password: P455w0rd
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
project:
  poster: posters/

base:
  url: "http://localhost:8080"
  
#logging:
#  level:
#    org.springframework : DEBUG


